# ============================================
# Distributed Cluster Environment Configuration
# ============================================
# Update these IPs when connecting laptops.
# After changing, run: python setup_cluster.py
# ============================================

# Master Node (JobManager) - Laptop 1
MASTER_IP= 10.12.70.214
MASTER_PORT=6123
REST_PORT=8081

# Worker Nodes (TaskManagers) - Laptops 2, 3, 4
WORKER1_IP=10.12.87.17
WORKER2_IP=CHANGE_ME
WORKER3_IP=CHANGE_ME

# Task Slots per Worker (how many parallel tasks each laptop runs)
TASK_SLOTS=4

# Parallelism (total = TASK_SLOTS * number_of_workers)
PARALLELISM=4
